{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "dynamic-feature-loader",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-feature-loader-3.6.302.18.aar",
          "url": "dynamic-feature-loader-3.6.302.18.aar",
          "size": 168054,
          "sha512": "02d05c5dd0f7ddee371e9e0fe2b056bd30a7a3e9d8ee5787ce952da66c79d740780274e8050cb0a694b8b40ed6248ecc91d61354f82468b9bf1ac7ded00dca51",
          "sha256": "d582b6e646e0282189c630bea23982613be8fa4c281bc9ccb0af8244d31288a4",
          "sha1": "4546b2b8c39a0109a7aa93e746b4e477d0640d25",
          "md5": "88714e3b70801cdf7048ea8e561eefc3"
        }
      ]
    },
    {
      "name": "productReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-feature-loader-3.6.302.18.aar",
          "url": "dynamic-feature-loader-3.6.302.18.aar",
          "size": 168054,
          "sha512": "02d05c5dd0f7ddee371e9e0fe2b056bd30a7a3e9d8ee5787ce952da66c79d740780274e8050cb0a694b8b40ed6248ecc91d61354f82468b9bf1ac7ded00dca51",
          "sha256": "d582b6e646e0282189c630bea23982613be8fa4c281bc9ccb0af8244d31288a4",
          "sha1": "4546b2b8c39a0109a7aa93e746b4e477d0640d25",
          "md5": "88714e3b70801cdf7048ea8e561eefc3"
        }
      ]
    }
  ]
}
