{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "historical_meetings",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "historical_meetings-3.6.302.18.aar",
          "url": "historical_meetings-3.6.302.18.aar",
          "size": 1777254,
          "sha512": "c160d7a28553e4569cdc8fecc0eef4929c3e790f88aa8aaadbb07b78827d71fd4619249504aac7a42a62fba4c613ec382af52d95c0ce0e6f666d288cf8ee4bde",
          "sha256": "e83ecc72928e6a1a41bb63ab21fbe8e58d2df7b3a21a082fc3c120e1c3f8e1f1",
          "sha1": "c9cabe86191191055b5b3bf7279568021da0f7ca",
          "md5": "14a7d85941298e5980789f9ac098590c"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.302.18"
          }
        }
      ],
      "files": [
        {
          "name": "historical_meetings-3.6.302.18.aar",
          "url": "historical_meetings-3.6.302.18.aar",
          "size": 1777254,
          "sha512": "c160d7a28553e4569cdc8fecc0eef4929c3e790f88aa8aaadbb07b78827d71fd4619249504aac7a42a62fba4c613ec382af52d95c0ce0e6f666d288cf8ee4bde",
          "sha256": "e83ecc72928e6a1a41bb63ab21fbe8e58d2df7b3a21a082fc3c120e1c3f8e1f1",
          "sha1": "c9cabe86191191055b5b3bf7279568021da0f7ca",
          "md5": "14a7d85941298e5980789f9ac098590c"
        }
      ]
    }
  ]
}
