{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "invite",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "invite-3.6.302.18.aar",
          "url": "invite-3.6.302.18.aar",
          "size": 826204,
          "sha512": "850ef543791c71aca70cf4f7de763bf86103c2e9633fb1d43842709356b4a9545e47f77580d45fca4154b9bd524e26ca5004c9ce91686dadc937091310a26896",
          "sha256": "95b7fa4795325a7439c391536d23f1011aa64e1b9cd6e8e8328d934513342b67",
          "sha1": "851d3b2fc607ccb36a90e3d7483a0a4dc5912f5e",
          "md5": "e1cd2081e0d7b41614ba79d547fd5267"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "invite-3.6.302.18.aar",
          "url": "invite-3.6.302.18.aar",
          "size": 826204,
          "sha512": "850ef543791c71aca70cf4f7de763bf86103c2e9633fb1d43842709356b4a9545e47f77580d45fca4154b9bd524e26ca5004c9ce91686dadc937091310a26896",
          "sha256": "95b7fa4795325a7439c391536d23f1011aa64e1b9cd6e8e8328d934513342b67",
          "sha1": "851d3b2fc607ccb36a90e3d7483a0a4dc5912f5e",
          "md5": "e1cd2081e0d7b41614ba79d547fd5267"
        }
      ]
    }
  ]
}
