{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "docs",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "docs-3.6.302.18.aar",
          "url": "docs-3.6.302.18.aar",
          "size": 372325,
          "sha512": "68d88d1d742995bdd8b1635b98130ab3b4f79fd25e238bcb3234996737f99aa28500d7aefa0f6ac59b4e9dae862f7b6f8a6b5a53bc793e761b612b55a849a53e",
          "sha256": "837657e7901a05356a854d46a7c59cd40d7d0fdf46032cd73a3bea272a061a7e",
          "sha1": "5642b107695d8138e8fd783b611585d23fe7db30",
          "md5": "708634a283066a5cfc6c583d77145849"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.302.18"
          }
        }
      ],
      "files": [
        {
          "name": "docs-3.6.302.18.aar",
          "url": "docs-3.6.302.18.aar",
          "size": 372325,
          "sha512": "68d88d1d742995bdd8b1635b98130ab3b4f79fd25e238bcb3234996737f99aa28500d7aefa0f6ac59b4e9dae862f7b6f8a6b5a53bc793e761b612b55a849a53e",
          "sha256": "837657e7901a05356a854d46a7c59cd40d7d0fdf46032cd73a3bea272a061a7e",
          "sha1": "5642b107695d8138e8fd783b611585d23fe7db30",
          "md5": "708634a283066a5cfc6c583d77145849"
        }
      ]
    }
  ]
}
