{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "module-core",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "auth",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "uikit",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "lottie",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "push",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.yqritc",
          "module": "recyclerview-flexibledivider",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "module-core-3.6.302.18.aar",
          "url": "module-core-3.6.302.18.aar",
          "size": 3268278,
          "sha512": "f79535d6be44ac53b811cd52f6310f4e6c3612fd2f23534b824798b98eb60843cde19b5a025cdc1202d7ab991d2ec683646bf7d372b84c14c8265004f747fffb",
          "sha256": "b2683331e701b73cfb3564035e04d2635ff7b6922ab348fcc4f99ffe1c644da4",
          "sha1": "8dfd8e9e14257c6b1d6881b8085c4ae9e506a608",
          "md5": "9bf66ad16aea069edaa7f4848de0b198"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet.third-party",
          "module": "xcast",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "auth",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "uikit",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "lottie",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "push",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.yqritc",
          "module": "recyclerview-flexibledivider",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "tcaptchawrapper",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "picture-selector",
          "version": {
            "requires": "1.1.31"
          }
        },
        {
          "group": "yt-parvati.yt-parvati-wemeet",
          "module": "yt-parvati-wemeet-resource",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "yt-parvati.yt-parvati-wemeet",
          "module": "yt-parvati-wemeet-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "yt-3d-avatar.wemeet",
          "module": "yt-3d-avatar-wemeet",
          "version": {
            "requires": "v2.2.12"
          }
        },
        {
          "group": "youtu.yt-mobile-sdk",
          "module": "libYTCommon",
          "version": {
            "requires": "v2.4.4_meeting"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-core-3.6.302.18.aar",
          "url": "module-core-3.6.302.18.aar",
          "size": 3268278,
          "sha512": "f79535d6be44ac53b811cd52f6310f4e6c3612fd2f23534b824798b98eb60843cde19b5a025cdc1202d7ab991d2ec683646bf7d372b84c14c8265004f747fffb",
          "sha256": "b2683331e701b73cfb3564035e04d2635ff7b6922ab348fcc4f99ffe1c644da4",
          "sha1": "8dfd8e9e14257c6b1d6881b8085c4ae9e506a608",
          "md5": "9bf66ad16aea069edaa7f4848de0b198"
        }
      ]
    }
  ]
}
