{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "reddot",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "reddot-3.6.302.18.aar",
          "url": "reddot-3.6.302.18.aar",
          "size": 50178,
          "sha512": "938f66211a08306f9715c6061eca59823c73488285dc1c6242002b8916d15d96f0eecc05bcbc3672ad7f86f354c4446c8a230d3db39eddbeea0e04480bf5d9f2",
          "sha256": "6e8cdd186499facda17fd437f5da8a91f7d1cdeb3f24e5b9733088fca514e558",
          "sha1": "fd5e7ff91d1e37f4b92a8dd146ab43e01bd81578",
          "md5": "3a95b5971f891da89619b41b8834d97e"
        }
      ]
    },
    {
      "name": "productReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wemeet-kapt",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.302.18"
          }
        }
      ],
      "files": [
        {
          "name": "reddot-3.6.302.18.aar",
          "url": "reddot-3.6.302.18.aar",
          "size": 50178,
          "sha512": "938f66211a08306f9715c6061eca59823c73488285dc1c6242002b8916d15d96f0eecc05bcbc3672ad7f86f354c4446c8a230d3db39eddbeea0e04480bf5d9f2",
          "sha256": "6e8cdd186499facda17fd437f5da8a91f7d1cdeb3f24e5b9733088fca514e558",
          "sha1": "fd5e7ff91d1e37f4b92a8dd146ab43e01bd81578",
          "md5": "3a95b5971f891da89619b41b8834d97e"
        }
      ]
    }
  ]
}
