{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "play-core-library",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "play-core-library-3.6.302.18.aar",
          "url": "play-core-library-3.6.302.18.aar",
          "size": 47477,
          "sha512": "0977a58b8eb7960bf3bae3b427d16711c37fb723b4d011a81bf9f1eba1a68093fa71a6919ec6a9a898323c974d9ddd5f8edee76f6d968fe69ba67879c1fa7122",
          "sha256": "4cbb3bb45b0cff5d0b32eed6883b7787f1aead259448293f1b5b5b64c94742d4",
          "sha1": "cfb4297969ae20fe7526654626eb06ae4d51751d",
          "md5": "7d0fe8318ff4e3a614f4ce08528c884d"
        }
      ]
    },
    {
      "name": "productReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.wemeet",
          "module": "dynamic-feature-loader",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-loader",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.302.18"
          }
        }
      ],
      "files": [
        {
          "name": "play-core-library-3.6.302.18.aar",
          "url": "play-core-library-3.6.302.18.aar",
          "size": 47477,
          "sha512": "0977a58b8eb7960bf3bae3b427d16711c37fb723b4d011a81bf9f1eba1a68093fa71a6919ec6a9a898323c974d9ddd5f8edee76f6d968fe69ba67879c1fa7122",
          "sha256": "4cbb3bb45b0cff5d0b32eed6883b7787f1aead259448293f1b5b5b64c94742d4",
          "sha1": "cfb4297969ae20fe7526654626eb06ae4d51751d",
          "md5": "7d0fe8318ff4e3a614f4ce08528c884d"
        }
      ]
    }
  ]
}
