{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "base-jni",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-jni-3.6.302.18.aar",
          "url": "base-jni-3.6.302.18.aar",
          "size": 42484,
          "sha512": "3fba223a5ad1301b28bc1b4b19de724fbab9a3305a2202e6af5bac3dfb674e70feb50c4d490d5c6b85e61f1fa0f4d9bbdc19f5227807b9a38134ea1197505e40",
          "sha256": "3e2d9fa954ef12f0316db64574bcd2661011bcd49565d032e15bd3a1bada7961",
          "sha1": "6df3519f12a81b70ad50ffa498d78688bb9181d9",
          "md5": "d7222c928e927f9b0f58180a519a22ae"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.302.18"
          }
        }
      ],
      "files": [
        {
          "name": "base-jni-3.6.302.18.aar",
          "url": "base-jni-3.6.302.18.aar",
          "size": 42484,
          "sha512": "3fba223a5ad1301b28bc1b4b19de724fbab9a3305a2202e6af5bac3dfb674e70feb50c4d490d5c6b85e61f1fa0f4d9bbdc19f5227807b9a38134ea1197505e40",
          "sha256": "3e2d9fa954ef12f0316db64574bcd2661011bcd49565d032e15bd3a1bada7961",
          "sha1": "6df3519f12a81b70ad50ffa498d78688bb9181d9",
          "md5": "d7222c928e927f9b0f58180a519a22ae"
        }
      ]
    }
  ]
}
