{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tencent.wemeet",
    "module": "meeting_room",
    "version": "3.6.302.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "productMainlandReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "meeting_room-3.6.302.18.aar",
          "url": "meeting_room-3.6.302.18.aar",
          "size": 319485,
          "sha512": "c6d837c32cd4b21180f7a3850dc1bfe1644da43ef595c5b3b4e433ed51c708e2668a698a29dfbe143e78ce8a993db414878d506354eed6c3b4091d0556f75b58",
          "sha256": "c3e2d2be9a0d1225fef559b275126fe3bdab986cc5cc5e355bc68b64cc2d3ece",
          "sha1": "5944cd8cfe4f645709725d3a64f1099c63ba4919",
          "md5": "41772d6fb6b179e914a584987dbbc9cc"
        }
      ]
    },
    {
      "name": "productMainlandReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "module-core",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "kt-extensions",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "common",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "wmp",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "reddot",
          "version": {
            "requires": "3.6.302.18"
          }
        },
        {
          "group": "com.tencent.wemeet",
          "module": "webview",
          "version": {
            "requires": "3.6.302.18"
          }
        }
      ],
      "files": [
        {
          "name": "meeting_room-3.6.302.18.aar",
          "url": "meeting_room-3.6.302.18.aar",
          "size": 319485,
          "sha512": "c6d837c32cd4b21180f7a3850dc1bfe1644da43ef595c5b3b4e433ed51c708e2668a698a29dfbe143e78ce8a993db414878d506354eed6c3b4091d0556f75b58",
          "sha256": "c3e2d2be9a0d1225fef559b275126fe3bdab986cc5cc5e355bc68b64cc2d3ece",
          "sha1": "5944cd8cfe4f645709725d3a64f1099c63ba4919",
          "md5": "41772d6fb6b179e914a584987dbbc9cc"
        }
      ]
    }
  ]
}
